export default defineAppConfig({
  pages: [
    // 主包仅保留 TabBar 页面和登录相关页面
    'pages/tab-home/index',
    'pages/tab-customer/index',
    'pages/tab-knowledge/index',
    'pages/tab-content/index',
    'pages/tab-profile/index',
    'pages/login/index',
    'pages/register/index',
    'pages/change-password/index',
    'pages/settings/index',
    'pages/course-detail/index',
  ],
  // 分包配置
  subPackages: [
    {
      root: 'package-content',
      pages: [
        'pages/quick-note/index',
        'pages/topic-planning/index',
        'pages/content-creation/index',
        'pages/content-system/index',
        'pages/inspiration/index',
        'pages/favorite-list/index',
        'pages/viral-system/index',
        'pages/viral-favorites/index',
        'pages/viral-remix/index',
        'pages/input-sources/index',
        'pages/news/index',
        'pages/lexicon-system/index',
        'pages/lexicon-manage/index',
        'pages/ai-assistant/index',
        'pages/multimedia/index',
      ],
    },
    {
      root: 'package-customer',
      pages: [
        'pages/customer-management/index',
        'pages/customer/index',
        'pages/customer/detail',
        'pages/customer/edit',
        'pages/customer/statistics',
        'pages/customer/churn-warning',
        'pages/customer/churn-analysis',
        'pages/customer/sales-target',
        'pages/customer/sales-dashboard',
        'pages/recycling-order/index',
        'pages/recycle/index',
        'pages/recycle/detail',
        'pages/recycle/edit',
        'pages/recycle/dashboard',
        'pages/equipment-orders/index',
        'pages/equipment-orders/detail',
        'pages/equipment-orders/create',
      ],
    },
    {
      root: 'package-knowledge',
      pages: [
        'pages/knowledge-share/index',
        'pages/knowledge-share/create',
        'pages/knowledge-share/edit',
        'pages/knowledge-share/detail',
        'pages/admin-knowledge-share/index',
        'pages/knowledge/product-manual/index',
        'pages/knowledge/product-manual/detail',
        'pages/knowledge/design-knowledge/index',
        'pages/knowledge/design-knowledge/detail',
        'pages/knowledge/category-list',
      ],
    },
    {
      root: 'package-live',
      pages: [
        'pages/live-data/index',
        'pages/live-data/import/index',
        'pages/live-data/list/index',
        'pages/live-data/detail/index',
        'pages/live-data/dashboard/index',
        'pages/live-data/traffic/index',
        'pages/live-data/interaction/index',
        'pages/live-data/conversion/index',
        'pages/live-data/analysis/index',
        'pages/live-data/admin/index',
      ],
    },
    {
      root: 'package-admin',
      pages: [
        'pages/admin/users/index',
        'pages/admin/user-data/index',
        'pages/admin/dashboard/index',
        'pages/admin/audit/index',
        'pages/admin/audit-logs/index',
        'pages/admin/lexicon-manage/index',
        'pages/admin/quick-note-manage/index',
        'pages/admin/quick-notes/index',
        'pages/admin/ai-report/index',
        'pages/admin/share-manage/index',
        'pages/admin/share-stats/index',
        'pages/admin/data-export/index',
        'pages/admin/customer-management/index',
        'pages/admin/recycle-management/index',
        'pages/admin/team-management/index',
        'pages/admin/team-detail/index',
        'pages/admin/team-create/index',
        'pages/admin/send-notification/index',
        'pages/admin/ai-management/index',
        'pages/admin/ai-models/index',
        'pages/admin/ai-modules/index',
        'pages/admin/ai-stats/index',
        'pages/admin/ai-settings/index',
        'pages/admin/course-manage/index',
        'pages/admin/course-create/index',
        'pages/admin/course-edit/index',
      ],
    },
    {
      root: 'package-team',
      pages: [
        'pages/team/index',
        'pages/team/announcement',
        'pages/team/task',
        'pages/team/chat',
        'pages/notification/index',
        'pages/notification-center/index',
        'pages/task-schedule/index',
      ],
    },
    {
      root: 'package-user',
      pages: [
        'pages/data-stats/index',
        'pages/avatar-editor/index',
        'pages/subscribe-message/index',
        'pages/file-parser/index',
        'pages/dev-tools/index',
      ],
    },
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#0a0a0b',
    navigationBarTitleText: '星厨房',
    navigationBarTextStyle: 'white',
    backgroundColor: '#0a0a0b'
  },
  permission: {
    'scope.userLocation': {
      desc: '您的位置信息将用于展示同城热点'
    }
  },
  // 移除 lazyCodeLoading 配置，避免生成循环引用的 comp 组件
  // lazyCodeLoading: 'requiredComponents',
  tabBar: {
    color: '#71717a',
    selectedColor: '#f59e0b',
    backgroundColor: '#141416',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/tab-home/index',
        text: '工作台',
        iconPath: './assets/tabbar/layout-dashboard.png',
        selectedIconPath: './assets/tabbar/layout-dashboard-active.png',
      },
      {
        pagePath: 'pages/tab-customer/index',
        text: '客资管理',
        iconPath: './assets/tabbar/users.png',
        selectedIconPath: './assets/tabbar/users-active.png',
      },
      {
        pagePath: 'pages/tab-knowledge/index',
        text: '知识库',
        iconPath: './assets/tabbar/book-open.png',
        selectedIconPath: './assets/tabbar/book-open-active.png',
      },
      {
        pagePath: 'pages/tab-profile/index',
        text: '我',
        iconPath: './assets/tabbar/user.png',
        selectedIconPath: './assets/tabbar/user-active.png',
      }
    ]
  }
})
